# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
vec_1 = np.zeros(10,dtype='int32')
print(vec_1)

[0 0 0 0 0 0 0 0 0 0]


3. Create a vector with values ranging from 10 to 49

In [4]:
vec_2 = np.arange(10,50)
print(vec_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [5]:
Shape = np.shape(vec_2)
print(Shape)

(40,)


5. Print the type of the previous array in question 3

In [6]:
print(type(vec_2))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/Anaconda\\Library\\include']
None


7. Print the dimension of the array in question 3


In [8]:
print(vec_1.ndim)

1


8. Create a boolean array with all the True values

In [10]:
bool_arr = np.array([True, True, True, True], dtype='bool')
print(bool_arr)

[ True  True  True  True]


9. Create a two dimensional array




In [11]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [12]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
arr_1 = np.array([1,2,3,4,5])
rev_arr_1 = np.flip(arr_1)
print(rev_arr_1)

[5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
null = np.zeros(10,dtype='int32')
null[4] = 1
print(null)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [16]:
arr_2 = np.array([1] *9)
arr_3d = arr_2.reshape(3,3)
print(arr_3d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [24]:
arr = np.array([1,2,3,4,5], dtype='float64')
print(arr.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [26]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

new_arr = arr1 * arr2

print(new_arr)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [28]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr_3 = arr1 < arr2
print(arr_3)

[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [29]:
arr_4 = np.arange(10)
odd = arr_4 % 2 != 0
print(arr_4[odd])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [30]:
arr_4[odd] = 1
print(arr_4)

[0 1 2 1 4 1 6 1 8 1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [31]:
arr = np.arange(10)
arr[5] = arr[6] = arr[7] = arr[8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [34]:
arr_5 = np.array([1] * 9)
arr_5_2d = arr_5.reshape(3, 3) 
arr_5_2d[1,1] = 0
print(arr_5_2d)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [35]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [38]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [42]:
arr_2d = np.arange(10).reshape(5,2)
sliced_Arr = arr_2d[0,]
print(sliced_Arr)

[0 1]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [43]:
arr_5 = np.arange(10).reshape(5,2)
sliced_Arr = arr_5[1,1]
print(sliced_Arr)

3


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [45]:
arr_5 = np.arange(10).reshape(2,5)
sliced_Arr = arr_5[[0,1],2]
print(sliced_Arr)

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [70]:
arr_random = np.array([np.random.randint(4,50) for x in range(100)]).reshape(10,10)
print(arr_random)
print("min value = " + str(arr_random.min()))

print("max value = " + str(arr_random.max()))


[[14 41  7 31 47 26 34 17 32  6]
 [ 4 49 49 32 19 28 40 23 21 11]
 [42 26 37 28 45 18 47 22 48 40]
 [18 11  8 47 44 42 10 25 41 33]
 [23 31 43 43  7 21  8 48 13 21]
 [24 30 24 48  4 28  6 10 27 30]
 [14 38 25 22 17 28 32  6  5 42]
 [37  8 40 46 18 30 11 21 19 36]
 [38 19 24 29 21 46 44 35 27 39]
 [14 27 42 22 45 24 36 45 35 48]]
min value = 4
max value = 49


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
same = a == b
print(a[same])

[2 2 4 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
match = a == b
print(a[match])

[2 2 4 4]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
find = names != 'Will'
print(data[find])

[[-1.23624676  1.6608875  -0.24292547  1.52558654]
 [-0.63552891 -0.69859004  1.82885819 -0.29877959]
 [-0.53822875  1.48655938 -0.03446724 -0.62604847]
 [ 0.40388744  1.2566915   0.8339034   0.54048835]
 [-0.43003922 -1.40681124  0.25213284 -0.76011077]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
find = (names != 'Will') & (names != 'Joe')
print(data[find])

[[ 0.19570784 -0.70123694 -0.89503278  0.95917336]
 [ 0.51167095 -0.60071999 -0.37154462  0.16839371]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [64]:
arr_7 = np.arange(1,16).reshape(5,3)
print(arr_7)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [65]:
arr_8 = np.arange(1,17).reshape(2,2,4)
print(arr_8)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [66]:
swaped = np.swapaxes(arr_8,0,2)
print(swaped)

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [69]:
arr_9 = np.array(range(10))
mid_arr = arr_9**(0.5)
SQ_arr_arg = mid_arr > 0.5
SQ_arr = mid_arr[SQ_arr_arg]
print(SQ_arr)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [4]:
arr_10 = np.array([np.random.randint(0,20) for x in range(12)])
arr_11 = np.array([np.random.randint(0,30) for x in range(12)])
print(np.maximum(arr_10,arr_11))

[26 19  5 26 25 18 18 28  6  6 10 11]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))


['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [84]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
arg = np.setdiff1d(a,b)
print(arg)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [51]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis=1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [49]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x@y)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [50]:
randArr = np.array([np.random.randint(0,40) for x in range(20)])
print(randArr)
print(np.cumsum(randArr))

[33  6 19 35 11 24 20 10 14 14 35 35  9 38 22 12 22 36 11 31]
[ 33  39  58  93 104 128 148 158 172 186 221 256 265 303 325 337 359 395
 406 437]
